name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_and_Run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        python manage.py migrate

    - name: Run Django server
      run: |
        python manage.py runserver 0.0.0.0:8000 &
      # You can add `wait` or `sleep` commands to give the server some time to start

    - name: Run health check on the server
      run: |
        curl http://127.0.0.1:8000/

    - name: Stop the server (optional, but useful)
      run: |
        pkill -f runserver
